
POST http://{{host}}/api/course/all
Content-Type: application/x-www-form-urlencoded


###


###

###
POST http://{{host}}/api/course/all
Content-Type: application/x-www-form-urlencoded

###

POST http://{{host}}/api/org/all
Content-Type: application/x-www-form-urlencoded


###

POST http://{{host}}/api/org/grouped
Content-Type: application/x-www-form-urlencoded

### user.login test

POST http://{{host}}/api/user/login
Content-Type: application/x-www-form-urlencoded

uid=test&password=123456

### user.register test

POST http://{{host}}/api/user/register
Content-Type: application/x-www-form-urlencoded

uid=cht&name=陈昊天&age=20&password=123456&rePassword=123456&sex=false&email=t1542462994@outlook.com

### user.state test

POST http://{{host}}/api/user/state
Content-Type: application/x-www-form-urlencoded

### user.logout test

POST http://{{host}}/api/user/logout
Content-Type: application/x-www-form-urlencoded

### org.create test

POST http://{{host}}/api/org/create
Content-Type: application/x-www-form-urlencoded

name=信息工程学院&description=计算机学院的组织&public=false

### org.create test2

POST http://{{host}}/api/org/create
Content-Type: application/x-www-form-urlencoded

name=软件工程01&description=软件工程的班级&parentId=1

### org.all test

POST http://{{host}}/api/org/all
Content-Type: application/x-www-form-urlencoded

### org.list test

POST http://{{host}}/api/org/list
Content-Type: application/x-www-form-urlencoded

### org.get test

POST http://{{host}}/api/org/get
Content-Type: application/x-www-form-urlencoded

orgId=1

### message.post test

POST http://{{host}}/api/message/post
Content-Type: application/x-www-form-urlencoded

type=ORGANIZATION&message=这是一则测试的消息&url=/org/1

### message.get test

POST http://{{host}}/api/message/get
Content-Type: application/x-www-form-urlencoded

### message.read test

POST http://{{host}}/api/message/read
Content-Type: application/x-www-form-urlencoded

messageId=4

### course.all test

POST http://{{host}}/api/course/all
Content-Type: application/x-www-form-urlencoded

### course.create test

POST http://{{host}}/api/course/create
Content-Type: application/x-www-form-urlencoded

name=计算机组成原理&info=计算机组成原理必修课程，其前修课程有&pic=uisafdsafsdfsd&public=false

### course.update test

POST http://{{host}}/api/course/update
Content-Type: application/x-www-form-urlencoded

id=61&name=软件工程&info=软件工程专业必修课程&pic=uisafdadfafadf&public=false

### course.delete test

POST http://{{host}}/api/course/delete
Content-Type: application/x-www-form-urlencoded

courseId=60

### course.createTag test

POST http://{{host}}/api/course/tag/create
Content-Type: application/x-www-form-urlencoded

courseId=61&name=编译语言

### course.removeTag test

POST http://{{host}}/api/course/tag/delete
Content-Type: application/x-www-form-urlencoded

courseId=61&tagId=1

### course.getChapters test

POST http://{{host}}/api/course/chapter/get
Content-Type: application/x-www-form-urlencoded

courseId=61

### course.createChapter test

POST http://{{host}}/api/course/chapter/create
Content-Type: application/x-www-form-urlencoded

courseId=61&name=第一章&index=0

### course.updateChapter test

POST http://{{host}}/api/course/chapter/update
Content-Type: application/x-www-form-urlencoded

courseId=61&chapterId=1&name=第二章

### course.moveChapter test

POST http://{{host}}/api/course/chapter/move
Content-Type: application/x-www-form-urlencoded

courseId=61&chapterId=1&index=0

### course.deleteChapter test

POST http://{{host}}/api/course/chapter/delete
Content-Type: application/x-www-form-urlencoded

courseId=61&chapterId=1