
### user.register GET action

GET http://{{host}}/user/register?uid=test1&name=test1&password=testpassword&email=test@test.com

### user.register POST action

POST http://{{host}}/user/register
Content-Type: application/x-www-form-urlencoded

uid=test1&name=test1&password=testpassword&email=test@test.com

### user.login POST action

POST http://{{host}}/user/login
Content-Type: application/x-www-form-urlencoded

uid=test1&password=testpassword

### user.register POST action expired at 2020/11/18

POST http://{{host}}/user/auto_login
Content-Type: application/x-www-form-urlencoded

uid=test1&token=60bec318-f25d-46d9-b422-289d27963834

### user.register POST action expired at 2020/11/11

POST http://{{host}}/user/auto_login
Content-Type: application/x-www-form-urlencoded

uid=test1&token=92402ae9-0a61-42ac-bf45-1ae518ea0c93

###